[project]
name = "yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ultralytics>=8.4.11",
    "numpy<2",
]

[tool.uv]
override-dependencies = [
    "opencv-python ; sys_platform == 'never'",
    "torch ; sys_platform == 'never'",
    "torchvision ; sys_platform == 'never'",
]
